// <auto-generated />
namespace BikeRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Originalversionofmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Originalversionofmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "202103291238360_Original version of models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
