// <auto-generated />
namespace BikeRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddExtraCustomerFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExtraCustomerFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202104031157347_AddExtraCustomerFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
